version: "2.4"
services:
    mqtt_client:
        build: 
            context: ./mqtt_client
        image: edge/mqttinfluxdbclient:1.0.0
        container_name: mqtt_influxdb_client
        volumes:
            - './cfg-data/:/cfg-data/'
        depends_on:
            - influxdb
        restart: unless-stopped
        networks: 
            - proxy-redirect
        mem_limit: 100mb
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"


    influxdb:
        image: influxdb:2.7
        container_name: influxdb
        ports:
        - "8086:8086"
        volumes:
        - influxdata:/var/lib/influxdb2
        restart: unless-stopped
        networks:
            - proxy-redirect
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

  
volumes:
    influxdata:
    grafanadata:

networks:
    proxy-redirect:
        external: true
        name: proxy-redirect

    

