version: "2.4"
services:
    mqtt_client:
        build: 
            context: ./mqtt_client
        image: edge/mqttinfluxdbclient:1.0.0
        container_name: mqtt_influxdb_client
        volumes:
            - './cfg-data/:/cfg-data/'
        depends_on:
            - influxdb
        restart: unless-stopped
        networks: 
            - proxy-redirect
        mem_limit: 100mb
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"


    influxdb: 
        build: 
           context: ./influxdb
        image: edge/influxdb:1.0.0
        container_name: influxdb
        ports:
            - "8087:8086"
        restart: unless-stopped
        volumes:
        - influxdata:/var/lib/influxdb
        - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
        mem_limit: 100mb
        networks: 
            - proxy-redirect
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"


    grafana: 
        build:
            context: ./grafana
        image: edge/grafana:1.0.0
        container_name: grafana
        ports: 
            - "33000:3000"
        restart: unless-stopped
        depends_on:
            - influxdb 
        volumes: 
            - grafanadata:/var/lib/grafana 
        networks: 
            - proxy-redirect
        mem_limit: 400mb
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
  
volumes:
    influxdata:
    grafanadata:

networks:
    proxy-redirect:
        external: true
        name: proxy-redirect

    

