version: "2.4"
services:
    mqtt_client:
        build: 
            context: ./mqtt_client
        image: edge/mqttinfluxdbclient:1.0.0
        container_name: mqtt_influxdb_client
        volumes:
            - './cfg-data/:/cfg-data/'
        depends_on:
            - influxdb
        restart: unless-stopped
        networks: 
            - proxy-redirect
        mem_limit: 100mb
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"


    influxdb:
        image: influxdb:2.7
        container_name: influxdb
        ports:
        - "8086:8086"
        environment:
            DOCKER_INFLUXDB_INIT_MODE: "setup"
            DOCKER_INFLUXDB_INIT_USERNAME: "adminedge@seat.es"
            DOCKER_INFLUXDB_INIT_PASSWORD: "E*123456"
            DOCKER_INFLUXDB_INIT_ORG: "SEAT S.A."
            DOCKER_INFLUXDB_INIT_BUCKET: "my-bucket"
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "my-secret-token"
        volumes:
        - influxdata:/var/lib/influxdb2
        mem_limit : 2048mb
        mem_reservation : 1024mb

        restart: unless-stopped
        networks:
            - proxy-redirect
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

  
volumes:
    influxdata:
    grafanadata:

networks:
    proxy-redirect:
        external: true
        name: proxy-redirect

    

